class LanguageModel {
  final String code;
  final String name;

  const LanguageModel(this.code, this.name);

  static const all = [
    LanguageModel('aa', 'Afar'),
    LanguageModel('ab', 'Abkhazian'),
    LanguageModel('af', 'Afrikaans'),
    LanguageModel('ak', 'Akan'),
    LanguageModel('am', 'Amharic'),
    LanguageModel('an', 'Aragonese'),
    LanguageModel('ar', 'Arabic'),
    LanguageModel('as', 'Assamese'),
    LanguageModel('av', 'Avaric'),
    LanguageModel('ay', 'Aymara'),
    LanguageModel('az', 'Azerbaijani'),
    LanguageModel('ba', 'Bashkir'),
    LanguageModel('be', 'Belarusian'),
    LanguageModel('bg', 'Bulgarian'),
    LanguageModel('bh', 'Bihari'),
    LanguageModel('bi', 'Bislama'),
    LanguageModel('bm', 'Bambara'),
    LanguageModel('bn', 'Bengali'),
    LanguageModel('bo', 'Tibetan'),
    LanguageModel('br', 'Breton'),
    LanguageModel('bs', 'Bosnian'),
    LanguageModel('ca', 'Catalan'),
    LanguageModel('ce', 'Chechen'),
    LanguageModel('ch', 'Chamorro'),
    LanguageModel('co', 'Corsican'),
    LanguageModel('cr', 'Cree'),
    LanguageModel('cs', 'Czech'),
    LanguageModel('cu', 'Church Slavic'),
    LanguageModel('cv', 'Chuvash'),
    LanguageModel('cy', 'Welsh'),
    LanguageModel('da', 'Danish'),
    LanguageModel('de', 'German'),
    LanguageModel('dv', 'Divehi'),
    LanguageModel('dz', 'Dzongkha'),
    LanguageModel('ee', 'Ewe'),
    LanguageModel('el', 'Greek'),
    LanguageModel('en', 'English'),
    LanguageModel('eo', 'Esperanto'),
    LanguageModel('es', 'Spanish'),
    LanguageModel('et', 'Estonian'),
    LanguageModel('eu', 'Basque'),
    LanguageModel('fa', 'Persian'),
    LanguageModel('ff', 'Fulah'),
    LanguageModel('fi', 'Finnish'),
    LanguageModel('fj', 'Fijian'),
    LanguageModel('fo', 'Faroese'),
    LanguageModel('fr', 'French'),
    LanguageModel('fy', 'Western Frisian'),
    LanguageModel('ga', 'Irish'),
    LanguageModel('gd', 'Scottish Gaelic'),
    LanguageModel('gl', 'Galician'),
    LanguageModel('gn', 'Guarani'),
    LanguageModel('gu', 'Gujarati'),
    LanguageModel('gv', 'Manx'),
    LanguageModel('ha', 'Hausa'),
    LanguageModel('he', 'Hebrew'),
    LanguageModel('hi', 'Hindi'),
    LanguageModel('ho', 'Hiri Motu'),
    LanguageModel('hr', 'Croatian'),
    LanguageModel('ht', 'Haitian'),
    LanguageModel('hu', 'Hungarian'),
    LanguageModel('hy', 'Armenian'),
    LanguageModel('hz', 'Herero'),
    LanguageModel('ia', 'Interlingua'),
    LanguageModel('id', 'Indonesian'),
    LanguageModel('ie', 'Interlingue'),
    LanguageModel('ig', 'Igbo'),
    LanguageModel('ii', 'Sichuan Yi'),
    LanguageModel('ik', 'Inupiaq'),
    LanguageModel('io', 'Ido'),
    LanguageModel('is', 'Icelandic'),
    LanguageModel('it', 'Italian'),
    LanguageModel('iu', 'Inuktitut'),
    LanguageModel('ja', 'Japanese'),
    LanguageModel('jv', 'Javanese'),
    LanguageModel('ka', 'Georgian'),
    LanguageModel('kg', 'Kongo'),
    LanguageModel('ki', 'Kikuyu'),
    LanguageModel('kj', 'Kuanyama'),
    LanguageModel('kk', 'Kazakh'),
    LanguageModel('kl', 'Kalaallisut'),
    LanguageModel('km', 'Khmer'),
    LanguageModel('kn', 'Kannada'),
    LanguageModel('ko', 'Korean'),
    LanguageModel('kr', 'Kanuri'),
    LanguageModel('ks', 'Kashmiri'),
    LanguageModel('ku', 'Kurdish'),
    LanguageModel('kv', 'Komi'),
    LanguageModel('kw', 'Cornish'),
    LanguageModel('ky', 'Kirghiz'),
    LanguageModel('la', 'Latin'),
    LanguageModel('lb', 'Luxembourgish'),
    LanguageModel('lg', 'Ganda'),
    LanguageModel('li', 'Limburgish'),
    LanguageModel('ln', 'Lingala'),
    LanguageModel('lo', 'Lao'),
    LanguageModel('lt', 'Lithuanian'),
    LanguageModel('lu', 'Luba-Katanga'),
    LanguageModel('lv', 'Latvian'),
    LanguageModel('mg', 'Malagasy'),
    LanguageModel('mh', 'Marshallese'),
    LanguageModel('mi', 'Maori'),
    LanguageModel('mk', 'Macedonian'),
    LanguageModel('ml', 'Malayalam'),
    LanguageModel('mn', 'Mongolian'),
    LanguageModel('mr', 'Marathi'),
    LanguageModel('ms', 'Malay'),
    LanguageModel('mt', 'Maltese'),
    LanguageModel('my', 'Burmese'),
    LanguageModel('na', 'Nauru'),
    LanguageModel('nb', 'Norwegian Bokmål'),
    LanguageModel('nd', 'North Ndebele'),
    LanguageModel('ne', 'Nepali'),
    LanguageModel('ng', 'Ndonga'),
    LanguageModel('nl', 'Dutch'),
    LanguageModel('nn', 'Norwegian Nynorsk'),
    LanguageModel('no', 'Norwegian'),
    LanguageModel('nr', 'South Ndebele'),
    LanguageModel('nv', 'Navajo'),
    LanguageModel('ny', 'Chichewa'),
    LanguageModel('oc', 'Occitan'),
    LanguageModel('oj', 'Ojibwa'),
    LanguageModel('om', 'Oromo'),
    LanguageModel('or', 'Oriya'),
    LanguageModel('os', 'Ossetian'),
    LanguageModel('pa', 'Punjabi'),
    LanguageModel('pi', 'Pali'),
    LanguageModel('pl', 'Polish'),
    LanguageModel('ps', 'Pashto'),
    LanguageModel('pt', 'Portuguese'),
    LanguageModel('qu', 'Quechua'),
    LanguageModel('rm', 'Romansh'),
    LanguageModel('rn', 'Rundi'),
    LanguageModel('ro', 'Romanian'),
    LanguageModel('ru', 'Russian'),
    LanguageModel('rw', 'Kinyarwanda'),
    LanguageModel('sa', 'Sanskrit'),
    LanguageModel('sc', 'Sardinian'),
    LanguageModel('sd', 'Sindhi'),
    LanguageModel('se', 'Northern Sami'),
    LanguageModel('sg', 'Sango'),
    LanguageModel('si', 'Sinhala'),
    LanguageModel('sk', 'Slovak'),
    LanguageModel('sl', 'Slovenian'),
    LanguageModel('sm', 'Samoan'),
    LanguageModel('sn', 'Shona'),
    LanguageModel('so', 'Somali'),
    LanguageModel('sq', 'Albanian'),
    LanguageModel('sr', 'Serbian'),
    LanguageModel('ss', 'Swati'),
    LanguageModel('st', 'Southern Sotho'),
    LanguageModel('su', 'Sundanese'),
    LanguageModel('sv', 'Swedish'),
    LanguageModel('sw', 'Swahili'),
    LanguageModel('ta', 'Tamil'),
    LanguageModel('te', 'Telugu'),
    LanguageModel('tg', 'Tajik'),
    LanguageModel('th', 'Thai'),
    LanguageModel('ti', 'Tigrinya'),
    LanguageModel('tk', 'Turkmen'),
    LanguageModel('tl', 'Tagalog'),
    LanguageModel('tn', 'Tswana'),
    LanguageModel('to', 'Tonga'),
    LanguageModel('tr', 'Turkish'),
    LanguageModel('ts', 'Tsonga'),
    LanguageModel('tt', 'Tatar'),
    LanguageModel('tw', 'Twi'),
    LanguageModel('ty', 'Tahitian'),
    LanguageModel('ug', 'Uighur'),
    LanguageModel('uk', 'Ukrainian'),
    LanguageModel('ur', 'Urdu'),
    LanguageModel('uz', 'Uzbek'),
    LanguageModel('ve', 'Venda'),
    LanguageModel('vi', 'Vietnamese'),
    LanguageModel('vo', 'Volapük'),
    LanguageModel('wa', 'Walloon'),
    LanguageModel('wo', 'Wolof'),
    LanguageModel('xh', 'Xhosa'),
    LanguageModel('yi', 'Yiddish'),
    LanguageModel('yo', 'Yoruba'),
    LanguageModel('za', 'Zhuang'),
    LanguageModel('zh', 'Chinese'),
    LanguageModel('zu', 'Zulu'),
  ];
}
